thec4aa/c4aa-org

- css/00-settings.css
- css/03-generic.css
Hey @laras126 see if this is useful...
> added all colors from design standards

- css/03-generic.css
Taking off the border radius from the header circle.
https://github.com/thec4aa/c4aa-org/issues/2
> our logo is not a circle

- functions.php
This is now showing up in the editor view but not the front end, for some reason. Can't figure it out, will create an issue.
> getting color palette working 

- css/03-generic.css
white background made it look goofy
> take out logo background

- css/03-generic.css
> Lose margin between header and first block

- css/03-generic.css
Thought I caught everything for #12, but no. There may be a more elegant or concise way of doing this.
> added more selectors

- css/04-blocks.css
> fix: comment out media block image sizing

- css/00-settings.css
- functions.php
> fix: remove 4 from namespace to sync up colors

- css/04-content.css
- functions.php
> Swank archive grid

- css/04-content.css
- functions.php
Fix for [full-width blocks issue](https://github.com/thec4aa/c4aa-org/issues/57)
> Created .c4aaa-excerpt-grid body  class

- functions.php
Starting to address #20. Buries it in bottom left column, but it's there. Will put effort into improving it if it ends up being useful, or abandon this effort and remove it.
> added dashboard widget

- css/03-generic.css
fix for issue [#47](https://github.com/thec4aa/c4aa-org/issues/47l)
> Removed spacing between header and top blockquote

- css/03-generic.css
Styled post meta data to stick to bottom as per [issue #14](https://github.com/thec4aa/c4aa-org/issues/14).
> Styled Post Meta Data

- css/03-generic.css
Styled h2, h3, and h4 per [issue #31](https://github.com/thec4aa/c4aa-org/issues/31).
> Styled h2, h3, h4

- css/03-generic.css
> fix: links are brand red

- css/03-generic.css
Making h1 a little smaller and adding some margins on the side. This may be all for naught when we add that banner we we're working on back in. Oh well...
@laras126 we're putting that banner back in right? I was thinking depending on the duotone we use we could have the banner be black, red, etc.
> styling h1

- css/03-generic.css
Closes #30
Originally I thought we'd do this with some other pages, but I thought of a better way for /newsletter and /contact
> h1 on home set to not display

- css/00-settings.css
- css/03-generic.css
- css/c4aa-clipPaths.css
- functions.php
- js/script.js
Randomized the clip-paths and rotations for headings. This should close #31.
> Clip-paths for headings

- css/00-settings.css
- css/c4aa-clipPaths.css
Edited the padding and margins to the headings as @slambert suggested on pull request #74.
> Offset h2, h3, h4 and adjust padding

- css/00-settings.css
closes #87
Also darkened red and lightened black.
I may regret the red thing, but I'll keep going.
> darken down grey for accessibility

- css/00-settings.css
- css/03-generic.css
work toward #45. Still needs polygon effect.
> Styling blockquotes/testimonials

- css/00-settings.css
- css/03-generic.css
@laras126 this is a branch of the "blockquotes" branch.
Please don't hate me. 
😬
> More colors in palette

- css/00-settings.css
- css/02-elements.css
- css/03-generic.css
- functions.php
styled with same font, weight, and letterspacing as headers.  Made default color the beige. Brought back the icons (for now, I'm 75% on that decision).
Closes #14
> post meta final polish for Issue #14

- css/00-settings.css
- css/03-generic.css
Started working on #11, still need to add clip-paths.
> Button Styling

- css/00-settings.css
- css/03-generic.css
- css/04-content.css
- css/c4aa-clipPaths.css
- js/script.js
This finishes he button styling #11 and the donate form styling on #10. It also makes text based input fields responsive, which resolves the issues with the contact form #33.
> Added button clip-paths and styled donation and contact forms

- css/c4aa-imageFilter.css
> fix: solve before/filter overlay on hover bug

- css/03-generic.css
Check out those commit messages!
> SL Pullquote Hyphen fix

- functions.php
Oversight. Just caught it. 
I'm gonna pull this one in.
> fix: didn't catch font listings in functions last time

- css/03-generic.css
- css/05-utilities.css
- footer.php
1. Removed auto-privacy policy link and moved it into the menu
2. Added non-breaking spaces to the phone number
3. Left align text on left side,  right align text on right side, vertically aligned the whole footer
4. Removed size references for magic hand svd
5. Trying out all red
> Polishing the footer

- css/03-generic.css
Closes #106 
I think I caught everything.
> fix link colors

- css/c4aa-clipPaths.css
> feat: override clippath for first pull quote

- build/main.css
- src/css/_03-generic.scss
> fix: padding for blockquotes

- functions.php
> Remove theme supoprt for jetpack responsive videos

- acf-json/group_5ce00da8eaae8.json
- build/main.css
- functions.php
- src/css/inc/_a-filter-child-img-themes.scss
@andrewheins  @slambert  I have added blue duotones. Issue fixes #272
> Add blue duotones to selections for featured images

- theme.json
Turning on and adding some features in themes.json. This version of theme.json didn't exist when we created this site and these options weren't available. Still early in the process, but these all feel pretty safe. Will merge into develop soon.
> Feat leverage theme.json

- src/css/_03-generic.scss
- theme.json
Should close https://github.com/thec4aa/c4aa-org/issues/4
(Also includes a fix of the dates within the latest news widget on the home page)
> Fix hr and separators

- functions.php
- src/css/_01-settings.css
- src/css/_02-elements.scss
- src/css/_03-generic.scss
- src/css/_c4aa-clipPaths.css
- src/css/_c4aa-editorStyles.css
> Add Basic Editor Styles 

- .vscode/tasks.json
- js/clipPaths.js
- js/editor.js
- src/css/_02-elements.scss
- src/css/_03-generic.scss
- src/css/_04-content.scss
- src/css/_c4aa-clipPaths.css
- src/css/_c4aa-editorStyles.css
- theme.json
Includes fixes for #302 and #250 and #207
> Feat: new button styles & form style updates

- src/css/_03-generic.scss
- src/css/_05-utilities.css
- src/css/_c4aa-clipPaths.css
- theme.json
> fix: get block spacer working

- functions.php
- theme.json
[fix: exclude mailto links from external link icon](https://github.com/thec4aa/c4aa-org/commit/98739b5275565874b4b0efc56f308a2af3488487)
Big refactor of themes.json and added some settings. Got a little lost with it.
add background images for blocks
extra pullquote removed
> incremental 

- js/clipPaths.js
- src/css/_02-elements.scss
- src/css/_03-generic.scss
- src/css/_04-content.scss
- src/css/_05-utilities.css
fix: people img layout and anti-aliasing
fix: rotate random not vice versa
> fix: lightbox button, rotate, anti-aliasing

- src/css/_01-settings.css
- src/css/_02-elements.scss
- src/css/_03-generic.scss
- src/css/_05-utilities.css
- src/css/_c4aa-editorStyles.css
All stuff discovered while designing the home page today...
> menu fixes, utilities, tablet formatting

- src/css/_01-settings.css
- src/css/_02-elements.scss
Refactoring and getting rid of bugs.
> fix image align changes

- src/css/_04-content.scss
will need to add javascript to style the colored images. Can't test this locally because related posts don't work.
> feat: styled related posts

- functions.php
- src/css/_02-elements.scss
> fix: outbound link on carousel #346

- js/clipPaths.js
- src/css/_02-elements.scss
- src/css/_03-generic.scss
- src/css/_c4aa-imageFilter.scss
> fix: style captions #349

- functions.php
- js/assorted.js
- src/css/_02-elements.scss
- src/css/_04-content.scss
- Adds javascript to help people choose a monthly donation with the Donate-a-tron 3001
- updates functions.php to load in javascript with versioning (this wasn't happening before)
- unifying spelling of formidable
- formidable color block styled
> Emphasize Monthy donations

- src/css/_04-content.scss
some weird character may have messed this up.
> fix: spacing problem

- src/css/_04-content.scss
It was showing up as a line when there was no error there
> fix: error message padding
